// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: getMessageId.proto

package getMessageIGrpcGateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetMessageIdServiceClient is the client API for GetMessageIdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetMessageIdServiceClient interface {
	GetMessageId(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error)
}

type getMessageIdServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetMessageIdServiceClient(cc grpc.ClientConnInterface) GetMessageIdServiceClient {
	return &getMessageIdServiceClient{cc}
}

func (c *getMessageIdServiceClient) GetMessageId(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error) {
	out := new(GetMessageResponse)
	err := c.cc.Invoke(ctx, "/getMessageId_proto.GetMessageIdService/GetMessageId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetMessageIdServiceServer is the server API for GetMessageIdService service.
// All implementations must embed UnimplementedGetMessageIdServiceServer
// for forward compatibility
type GetMessageIdServiceServer interface {
	GetMessageId(context.Context, *GetMessageRequest) (*GetMessageResponse, error)
	mustEmbedUnimplementedGetMessageIdServiceServer()
}

// UnimplementedGetMessageIdServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGetMessageIdServiceServer struct {
}

func (UnimplementedGetMessageIdServiceServer) GetMessageId(context.Context, *GetMessageRequest) (*GetMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessageId not implemented")
}
func (UnimplementedGetMessageIdServiceServer) mustEmbedUnimplementedGetMessageIdServiceServer() {}

// UnsafeGetMessageIdServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetMessageIdServiceServer will
// result in compilation errors.
type UnsafeGetMessageIdServiceServer interface {
	mustEmbedUnimplementedGetMessageIdServiceServer()
}

func RegisterGetMessageIdServiceServer(s grpc.ServiceRegistrar, srv GetMessageIdServiceServer) {
	s.RegisterService(&GetMessageIdService_ServiceDesc, srv)
}

func _GetMessageIdService_GetMessageId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetMessageIdServiceServer).GetMessageId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/getMessageId_proto.GetMessageIdService/GetMessageId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetMessageIdServiceServer).GetMessageId(ctx, req.(*GetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetMessageIdService_ServiceDesc is the grpc.ServiceDesc for GetMessageIdService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetMessageIdService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "getMessageId_proto.GetMessageIdService",
	HandlerType: (*GetMessageIdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessageId",
			Handler:    _GetMessageIdService_GetMessageId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "getMessageId.proto",
}
